=== TU-Berlin-DIMA/clickstream-gen/specification/specification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.dima.tu-berlin.de/myriad/specification" xmlns:myriad="http://www.dima.tu-berlin.de/myriad/specification" elementFormDefault="qualified">

  <!-- permitted root elements -->

  <xs:element name="generator_specification" type="myriad:generator_specification" />
  <xs:element name="generator_catalog" type="myriad:generator_catalog" />

  <!-- generator_specification root type -->

  <xs:complexType name="generator_specification">
    <xs:sequence>
      <xs:element name="imports" type="myriad:imports_container" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Catalog imports container.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="parameters" type="myriad:parameters_container" minOccurs="0">
        <xs:annotation>
          <xs:documentation>A list of global generator parameters.</xs:documentation>
        </xs:annotation>
        <xs:unique name="specification_parameter_name">
          <xs:selector xpath=".//myriad:parameter" />
          <xs:field xpath="@key"></xs:field>
        </xs:unique>
      </xs:element>
      <xs:element name="functions" type="myriad:functions" minOccurs="0">
        <xs:annotation>
          <xs:documentation>A list of named probability functions.</xs:documentation>
        </xs:annotation>
        <xs:unique name="specification_function_name">
          <xs:selector xpath=".//myriad:function" />
          <xs:field xpath="@key"></xs:field>
        </xs:unique>
      </xs:element>
      <xs:element name="enum_sets" type="myriad:enum_sets" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Enumerations used in the described domain model.</xs:documentation>
        </xs:annotation>
        <xs:unique name="specification_enum_set_name">
          <xs:selector xpath=".//myriad:enum_set" />
          <xs:field xpath="@key" />
        </xs:unique>
      </xs:element>
      <xs:element name="string_sets" type="myriad:string_sets" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Finite string sets used in the described domain model.</xs:documentation>
        </xs:annotation>
        <xs:unique name="specification_string_set_name">
          <xs:selector xpath=".//myriad:string-set" />
          <xs:field xpath="@key" />
        </xs:unique>
      </xs:element>
      <xs:element name="record_sequences" type="myriad:record_sequences">
        <xs:annotation>
          <xs:documentation>The record sequences produced by this generator.</xs:documentation>
        </xs:annotation>
        <xs:unique name="specification_record_sequence_name">
          <xs:selector xpath="./*" />
          <xs:field xpath="@key" />
        </xs:unique>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <!-- generator_catalog root type -->

  <xs:complexType name="generator_catalog">
    <xs:sequence>
      <xs:group ref="myriad:imports" />
      <xs:element name="parameters" type="myriad:parameters_container" minOccurs="0">
        <xs:annotation>
          <xs:documentation>A list of generator parameters for this catalog.</xs:documentation>
        </xs:annotation>
        <xs:unique name="catalog_parameter_name">
          <xs:selector xpath=".//myriad:parameter" />
          <xs:field xpath="@key"></xs:field>
        </xs:unique>
      </xs:element>
      <xs:element name="functions" type="myriad:functions" minOccurs="0">
        <xs:annotation>
          <xs:documentation>A list of functions for this catalog.</xs:documentation>
        </xs:annotation>
        <xs:unique name="catalog_function_name">
          <xs:selector xpath=".//myriad:function" />
          <xs:field xpath="@key"></xs:field>
        </xs:unique>
      </xs:element>
      <xs:element name="string_sets" type="myriad:string_sets" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Finite string sets for this catalog.</xs:documentation>
        </xs:annotation>
        <xs:unique name="catalog_string_set_name">
          <xs:selector xpath=".//myriad:string-set" />
          <xs:field xpath="@key" />
        </xs:unique>
      </xs:element>
      <xs:element name="enum_sets" type="myriad:enum_sets" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Enumerations for this catalog.</xs:documentation>
        </xs:annotation>
        <xs:unique name="catalog_enum_set_name">
          <xs:selector xpath=".//myriad:enum_set" />
          <xs:field xpath="@key" />
        </xs:unique>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <!-- imports -->
  <xs:group name="imports">
    <xs:sequence>
      <xs:element name="import" type="myriad:import" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:group>
  <xs:complexType name="imports_container">
    <xs:group ref="myriad:imports" />
  </xs:complexType>
  <xs:complexType name="import">
    <xs:attribute name="path" type="xs:string" use="required" />
    <xs:attribute name="namespace" type="xs:NCName" use="required" />
  </xs:complexType>

  <!-- parameters and arguments -->

  <!-- parameters -->
  <xs:group name="parameters">
    <xs:sequence>
      <xs:element name="parameter" type="myriad:parameter" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:group>
  <xs:complexType name="parameters_container">
    <xs:group ref="myriad:parameters" />
  </xs:complexType>
  <xs:complexType name="parameter">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="key" type="xs:NCName" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <!-- arguments -->
  <xs:group name="arguments">
    <xs:sequence>
      <xs:element name="argument" type="myriad:argument" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:group>
  <xs:complexType name="arguments_container">
    <xs:group ref="myriad:arguments" />
  </xs:complexType>
  <xs:complexType name="argument">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="argument" type="myriad:argument" />
    </xs:choice>
    <xs:attribute name="key" type="xs:string" use="required" />
    <xs:attribute name="type" type="xs:string" use="required" />
    <xs:attribute name="ref" type="xs:string" />
    <xs:attribute name="value" type="xs:string" />
  </xs:complexType>

  <!-- string / enum set items -->
  <xs:group name="items">
    <xs:sequence>
      <xs:element name="item" type="myriad:item" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:group>
  <xs:complexType name="item">
    <xs:sequence>
      <xs:element name="probability" type="myriad:probability-point-context" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="value" type="xs:string" use="required" />
  </xs:complexType>

  <!-- functions -->

  <xs:complexType name="functions">
    <xs:sequence>
      <xs:element name="function" type="myriad:function" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <!-- function -->
  <xs:complexType name="function">
    <xs:choice>
      <xs:element name="argument" type="myriad:argument" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="probability" type="myriad:probability-point-inline" minOccurs="0" maxOccurs="unbounded" />
    </xs:choice>
    <xs:attribute name="key" type="xs:string" use="required" />
    <xs:attribute name="type" type="xs:Name" use="required" />
  </xs:complexType>
  <!-- probability points for the custom discrete probability type -->
  <xs:complexType name="probability-point-inline">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="argument" type="xs:int" use="required" />
        <xs:attribute name="value" type="xs:double" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <!-- in-condext defined probability points -->
  <xs:complexType name="probability-point-context">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="function" type="xs:string" use="required" />
        <xs:attribute name="value" type="xs:double" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <!-- string-sets -->

  <xs:complexType name="string_sets">
    <xs:sequence>
      <xs:element name="string_set" type="myriad:string_set" minOccurs="0" maxOccurs="unbounded">
        <xs:unique name="string_set_item_value">
          <xs:selector xpath=".//myriad:item" />
          <xs:field xpath="@value" />
        </xs:unique>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="string_set">
    <xs:group ref="myriad:items" />
    <xs:attribute name="key" type="xs:NCName" use="required" />
  </xs:complexType>

  <!-- enum_sets -->

  <xs:complexType name="enum_sets">
    <xs:sequence>
      <xs:element name="enum_set" type="myriad:enum_set" minOccurs="0" maxOccurs="unbounded">
        <xs:unique name="enum_set_item_value">
          <xs:selector xpath=".//myriad:item" />
          <xs:field xpath="@value" />
        </xs:unique>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="enum_set">
    <xs:sequence>
      <xs:element name="item" type="myriad:item" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="key" type="xs:NCName" use="required" />
  </xs:complexType>

  <!-- record sequences -->

  <xs:complexType name="record_sequences">
    <xs:sequence>
      <xs:element name="random_sequence" type="myriad:random_sequence" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="random_sequence">
    <xs:sequence>
      <xs:element name="record_type" type="myriad:record_type" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="cardinality_estimator" type="myriad:cardinality_estimator" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="hydrators" type="myriad:hydrators" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="hydration_plan" type="myriad:hydration_plan" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="generator_tasks" type="myriad:generator_tasks" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="key" type="xs:NCName" use="required" />
  </xs:complexType>
  <xs:complexType name="record_type">
    <xs:sequence>
      <xs:element name="field" type="myriad:field_type" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="field_type">
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="type" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="hydrators">
    <xs:sequence>
      <xs:element name="hydrator" type="myriad:hydrator" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="cardinality_estimator">
    <xs:group ref="myriad:arguments" />
    <xs:attribute name="type" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="hydrator">
    <xs:group ref="myriad:arguments" />
    <xs:attribute name="key" type="xs:NCName" use="required" />
    <xs:attribute name="type" type="xs:NCName" use="required" />
  </xs:complexType>
  <xs:complexType name="hydration_plan">
    <xs:sequence>
      <xs:element name="hydrator_ref" type="myriad:hydrator_ref" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="hydrator_ref">
    <xs:attribute name="ref" type="xs:NCName" />
  </xs:complexType>
  <xs:complexType name="generator_tasks">
    <xs:sequence>
      <xs:element name="generator_task" type="myriad:generator_task" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="generator_task">
    <xs:group ref="myriad:arguments" />
    <xs:attribute name="key" type="xs:NCName" use="required" />
    <xs:attribute name="type" type="xs:NCName" use="required" />
  </xs:complexType>
</xs:schema>

=== TU-Berlin-DIMA/clickstream-gen/specification/clickstreamgen-specification.xml
<?xml version="1.0" encoding="UTF-8"?>
<generator_specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.dima.tu-berlin.de/myriad/specification" xsi:schemaLocation="http://www.dima.tu-berlin.de/myriad/specification specification.xsd">

  <!-- catalog imports -->
  <imports>
    <import path="catalog/census.us.xml" namespace="census.us" />
  </imports>

  <!-- configurable parameters -->
  <parameters>
    <!-- user parameters -->
    <parameter key="user.output_file">user.json</parameter>
    <!-- user_connections parameters -->
    <parameter key="user_connections.output_file">user_connections.json</parameter>
    <parameter key="user_connections.connections_cardinality">100</parameter>
    <parameter key="user_connections.cluster_size">200</parameter>
    <parameter key="user_connections.cluster_connections_factor">0.8</parameter>
  </parameters>

  <!-- function configuration -->
  <functions>
    <function key="Pr[in_cluster_connection]" type="pareto_probability">
      <argument key="x_min">1</argument>
      <argument key="alpha">1</argument>
    </function>
  </functions>

  <!-- enumeration types -->
  <enum_sets>
    <enum_set key="Gender">
      <item value="Male" />
      <item value="Female" />
    </enum_set>
    <enum_set key="Locale">
      <item value="US" />
      <item value="CA" />
    </enum_set>
  </enum_sets>

  <record_sequences>
    <!-- users -->
    <random_sequence key="user">
      <record_type>
        <field name="id" type="I64u" />
        <field name="locale" type="Locale" />
        <field name="gender" type="Gender" />
        <field name="first_name" type="String" />
        <field name="last_name" type="String" />
      </record_type>
      <cardinality_estimator type="linear_scale_estimator">
        <argument key="base_cardinality" type="I64u" value="%user_connections.sequence.base_cardinality%" />
      </cardinality_estimator>
      <hydrators>
        <hydrator key="id_hydrator" type="randomized_sequence_hydrator">
          <argument key="field" type="field_ref" ref="id" />
          <argument key="cardinality" type="long" value="%user.sequence.cardinality%" />
        </hydrator>
        <hydrator key="locale_hydrator" type="enum_set_hydrator">
          <argument key="field" type="field_ref" ref="locale" />
          <argument key="probability" type="function_ref" ref="Pr[locale]" />
        </hydrator>
        <hydrator key="gender_hydrator" type="enum_set_hydrator">
          <argument key="field" type="field_ref" ref="gender" />
          <argument key="probability" type="function_ref" ref="census.us:Pr[gender]" />
        </hydrator>
        <hydrator key="first_name_hydrator" type="conditional_hydrator">
          <argument key="field" type="field_ref" ref="first_name" />
          <argument key="condition_field" type="field_ref" ref="gender" />
          <argument key="choices" type="map">
            <argument key="Male" type="hydrator_ref" ref="male_name_hydrator" />
            <argument key="Female" type="hydrator_ref" ref="female_name_hydrator" />
          </argument>
        </hydrator>
        <hydrator key="male_name_hydrator" type="static_set_hydrator">
          <argument key="field" type="field_ref" ref="first_name" />
          <argument key="set" type="set_ref" ref="male_names" />
          <argument key="probability" type="function_ref" ref="census.us:Pr[male_names]" />
        </hydrator>
        <hydrator key="female_name_hydrator" type="static_set_hydrator">
          <argument key="field" type="field_ref" ref="first_name" />
          <argument key="set" type="set_ref" ref="female_names" />
          <argument key="probability" type="function_ref" ref="census.us:Pr[female_names]" />
        </hydrator>
      </hydrators>
      <hydration_plan>
        <hydrator_ref ref="id_hydrator" />
        <hydrator_ref ref="gender_hydrator" />
        <hydrator_ref ref="first_name_hydrator" />
      </hydration_plan>
      <generator_tasks>
        <generator_task key="user.generate" type="partitioned_iterator" />
      </generator_tasks>
    </random_sequence>

    <!-- user connections -->
    <random_sequence key="user_connections">
      <record_type>
        <field name="id" type="I64u" />
        <field name="cluster_id" type="I64u" />
        <field name="cluster_interval" type="Interval" />
        <field name="connections_count" type="vector[I64u]" />
        <field name="connections" type="vector[I64u]" />
      </record_type>
      <cardinality_estimator type="linear_scale_estimator">
        <argument key="base_cardinality" type="I64u" value="%user_connections.sequence.base_cardinality%" />
      </cardinality_estimator>
      <hydrators>
        <hydrator key="id_hydrator" type="randomized_sequence_hydrator">
          <argument key="field" type="field_ref" ref="id" />
          <argument key="cardinality" type="long" value="%user_connections.sequence.cardinality%" />
        </hydrator>
        <hydrator key="connections_count_hydrator" type="const_hydrator">
          <argument key="field" type="field_ref" ref="connections_count" />
          <argument key="const_value" type="I64u" value="%user_connections.connections_count%" />
        </hydrator>
        <hydrator key="cluster_id_hydrator" type="clustered_sequence_hydrator">
          <argument key="field" type="field_ref" ref="cluster_id" />
          <argument key="interval_field" type="field_ref" ref="cluster_interval" />
          <argument key="const_value" type="I16u" value="%user_connections.connections_count%" />
          <argument key="cardinality" type="I16u" value="${ %user_connections.sequence.cardinality% / %user_connections.cluster_size% }" />
          <argument key="probability" type="function_ref" ref="core:Pr[uniform]" />
        </hydrator>
        <hydrator key="connections_hydrator" type="repeated_hydrator">
          <argument key="field" type="field_ref" ref="connections" />
          <argument key="count_field" type="field_ref" ref="connections_count" />
          <argument key="inner_hydrator" type="hydrator_ref" />
        </hydrator>
        <hydrator key="connection_hydrator" type="clustered_reference_hydrator">
          <argument key="field" type="field_ref" ref="connections" />
          <argument key="restriction_interval_field" type="field_ref" ref="cluster_interval" />
          <argument key="probability" type="function_ref" ref="Pr[in_cluster_connection]" />
        </hydrator>
      </hydrators>
      <hydration_plan>
        <hydrator_ref ref="id_hydrator" />
        <hydrator_ref ref="cluster_id_hydrator" />
        <hydrator_ref ref="connections_count_hydrator" />
        <hydrator_ref ref="connections_hydrator" />
      </hydration_plan>
      <generator_tasks>
        <generator_task key="user_connections.generate" type="partitioned_iterator" />
      </generator_tasks>
    </random_sequence>
  </record_sequences>
</generator_specification>

=== TU-Berlin-DIMA/clickstream-gen/specification/catalog/census.us.xml
<?xml version="1.0" encoding="UTF-8"?>
<generator_catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.dima.tu-berlin.de/myriad/specification" xsi:schemaLocation="http://www.dima.tu-berlin.de/myriad/specification ../specification.xsd">

  <!-- function configuration -->
  <functions>
    <function key="Pr[male_name]" type="custom_discrete_probability" />
    <function key="Pr[female_name]" type="custom_discrete_probability" />
    <function key="Pr[surname]" type="custom_discrete_probability" />
    <function key="Pr[gender]" type="custom_discrete_probability">
      <probability argument="0" value='0.493' /> <!-- Male probability -->
      <probability argument="1" value='0.507' /> <!-- Female probability -->
    </function>
  </functions>

  <!-- string sets -->
  <string_sets>
    <!-- male first names -->
    <string_set key="male_names">
      <item value="James">
        <probability function="Pr[male_name]" value='0.0372726560947861000' />
      </item>
      <item value="John">
        <probability function="Pr[male_name]" value='0.0367004386998328000' />
      </item>
      <item value="Robert">
        <probability function="Pr[male_name]" value='0.0352642857944282000' />
      </item>
    </string_set>
  </string_sets>

</generator_catalog>
